//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountInformation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountInformation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccountInformation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountInformation_Email_.
        /// </summary>
        internal static string AccountInformation_Email_Length {
            get {
                return ResourceManager.GetString("AccountInformation_Email_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address is required.
        /// </summary>
        internal static string AccountInformation_Email_Required {
            get {
                return ResourceManager.GetString("AccountInformation_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Password Confirmation fields must be equal.
        /// </summary>
        internal static string AccountInformation_PasswordConfirmation_Equality {
            get {
                return ResourceManager.GetString("AccountInformation_PasswordConfirmation_Equality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a password confirmation.
        /// </summary>
        internal static string AccountInformation_PasswordConfirmation_Required {
            get {
                return ResourceManager.GetString("AccountInformation_PasswordConfirmation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters long..
        /// </summary>
        internal static string AccountInformation_Password_Length {
            get {
                return ResourceManager.GetString("AccountInformation_Password_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a password.
        /// </summary>
        internal static string AccountInformation_Password_Required {
            get {
                return ResourceManager.GetString("AccountInformation_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Security Answer must be a string with a maximum length of 100..
        /// </summary>
        internal static string AccountInformation_SecurityAnswer_Length {
            get {
                return ResourceManager.GetString("AccountInformation_SecurityAnswer_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an answer to your security question.
        /// </summary>
        internal static string AccountInformation_SecurityAnswer_Required {
            get {
                return ResourceManager.GetString("AccountInformation_SecurityAnswer_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Security Question must be a string with a maximum length of 100..
        /// </summary>
        internal static string AccountInformation_SecurityQuestion_Length {
            get {
                return ResourceManager.GetString("AccountInformation_SecurityQuestion_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a security question.
        /// </summary>
        internal static string AccountInformation_SecurityQuestion_Required {
            get {
                return ResourceManager.GetString("AccountInformation_SecurityQuestion_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Username must be a string with a maximum length of 10..
        /// </summary>
        internal static string AccountInformation_Username_Length {
            get {
                return ResourceManager.GetString("AccountInformation_Username_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a username.
        /// </summary>
        internal static string AccountInformation_Username_Required {
            get {
                return ResourceManager.GetString("AccountInformation_Username_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
